### ISSUE TITLE
Rename Module and Improve Build Pipeline to Increase Visibility and Reliability

### ISSUE THREAD

**Issue by JPRuskin** [chocolatey-community/chocolatey-au#32]
We are missing the ability to build and release this module.

It's been agreed that before we can start integrating PRs and fixing issues, we'll need a way to build, test, and release this module.

We should:
- Add a TeamCity build that can sign and publish the module to PowerShellGallery and the CCR
- Add a GitHub Actions build that the community can use to build and test the module without signing
- Change to SemVer v2 with the ID change
- Release an initial 1.0.0 with no functional difference to the existing module

**Comment by corbob** [comment]
Not entirely sure why this didn't get closed automatically. It has been fixed with #42 .
