### ISSUE TITLE
Issue templates are confusing

### ISSUE THREAD

**Issue by flcdrg** [chocolatey-community/chocolatey-au#51]
I went to create a new issue and at first glance the choices were a) create a new release or b) a security vulnerability. I didn't want either of these. Only on closer inspection (in the fine print!) did I notice you can click on the 'blank issue' link. 

![image](https://github.com/chocolatey-community/chocolatey-au/assets/384747/e0fe2b93-0be2-4f52-a934-f389402f3225)

I think you need another issue template so it is obvious for folks who just want to rasise bug/feature requests.

**Comment by pauby** [comment]
Thanks for picking up on this @flcdrg. We missed adding the other templates when creating and working on the repository. 

This should be fixed by https://github.com/chocolatey/.github/pull/47. I'll leave this open until that has synced properly.

**Comment by pauby** [comment]
Thsi has been synced and #56 has been merged.
